version: '2'

services:
    openhr20:
        build: .
        restart: unless-stopped
        image: juha63/openhr20
        ports:
            - '${HTTP_PORT}:80'
        volumes:
            - ${CONFIG}/openhr20:/config
        devices:
             - '${SERIAL_PORT}:/dev/ttyUSB-HR20'
        environment:
            - TZ
        container_name: openhr20new

