version: '2'

services:
    openhr20:
        build: .
        restart: unless-stopped
        image: tezet/openhr20
        ports:
            - '${HTTP_PORT}:80'
        volumes:
            - ${CONFIG}/openhr20:/config
        environment:
            - TZ
